global:
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#dmitry_ilyasov'
