version: '3.3'
services:
  post_db:
    env_file:
      - ./.env
    image: mongo:${VER_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    env_file:
      - ./.env
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${HOSTPORT}:${VMPORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    env_file:
      - ./.env
    image: ${USERNAME}/post:${VER_POST}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VER_COMMENT}
    env_file:
      - ./.env
    networks:
      - front_net
      - back_net
volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_NET}
  back_net:
    ipam:
      config:
        - subnet: ${BACK_NET}
